nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000/']
        allow_headers: ['*']
        allow_methods: ['*']
        expose_headers: ['Content-Type', 'X-Custom-Header', 'Access-Control-Allow-Origin']
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['X-Requested-With', 'Content-Type', 'Authorization']
            allow_methods: ['*']
            expose_headers: ['Content-Type', 'X-Custom-Header', 'Access-Control-Allow-Origin']